import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import "../styles.css";
import { createCustomer, createOrder, getCustomers, getDashboard, getOrders, getProducts, updateOrderStatus, updateProduct, updateShipment, getInvoice, getBusinessSettings, updateBusinessSettings, login as crmLogin, logout, getPublicTracking } from "../lib/api/crm.functions";

export const Route = createFileRoute("/")({
  component: CRM,
  server:{handlers:{POST:async({request})=>{
    const body=await request.json().catch(()=>null) as any;
    const {isAuthenticated,requireDb,makeSessionCookie,clearSessionCookie}=await import("../lib/crm-auth.server");
    const {bindings}=await import("../lib/bindings.server");
    if(!body?.action)return Response.json({error:"Missing action"},{status:400});
    if(body.action==="login"){
      const secret=bindings().CRM_PASSWORD;
      if(!secret)return Response.json({error:"CRM_PASSWORD is not configured."},{status:503});
      const supplied=typeof body.password==="string"?body.password:"";
      const [a,b]=await Promise.all([crypto.subtle.digest("SHA-256",new TextEncoder().encode(supplied)),crypto.subtle.digest("SHA-256",new TextEncoder().encode(secret))]);
      const aa=new Uint8Array(a),bb=new Uint8Array(b);let diff=0;for(let i=0;i<aa.length;i++)diff|=aa[i]^bb[i];
      if(supplied.length>256||diff!==0)return Response.json({error:"Invalid password"},{status:401});
      return Response.json({ok:true},{headers:{"Set-Cookie":await makeSessionCookie()}});
    }
    if(body.action==="logout")return Response.json({ok:true},{headers:{"Set-Cookie":clearSessionCookie()}});
    if(body.action==="track"){
      if(typeof body.id!=="string"||!body.id)return Response.json({error:"Invalid tracking id"},{status:400});
      const db=requireDb();const row=await db.prepare("SELECT o.order_no,o.status,s.courier,s.awb FROM orders o LEFT JOIN shipments s ON s.order_id=o.id WHERE o.id=?").bind(body.id).first();
      return Response.json(row??null);
    }
    const db=requireDb();
    if(body.action==="dashboard"){
      const [o,c,s,d,p]=await Promise.all([db.prepare("SELECT COUNT(*) n FROM orders").first<any>(),db.prepare("SELECT COUNT(*) n FROM customers").first<any>(),db.prepare("SELECT COUNT(*) n FROM orders WHERE status IN ('SHIPPED','OUT_FOR_DELIVERY')").first<any>(),db.prepare("SELECT COUNT(*) n FROM orders WHERE status='DELIVERED'").first<any>(),db.prepare("SELECT COUNT(*) n FROM orders WHERE status IN ('NEW','PACKED')").first<any>()]);
      const recent=await db.prepare("SELECT o.id,o.order_no,o.status,o.payment_status,o.total_paise,o.created_at,c.name,c.phone FROM orders o JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT 8").all();
      return Response.json({metrics:{orders:o?.n??0,customers:c?.n??0,shipped:s?.n??0,delivered:d?.n??0,pending:p?.n??0},recent:recent.results??[]});
    }
    if(body.action==="customers"){const r=await db.prepare("SELECT * FROM customers ORDER BY created_at DESC").all();return Response.json(r.results??[])}
    if(body.action==="products"){const r=await db.prepare("SELECT * FROM products WHERE active=1 ORDER BY name").all();return Response.json(r.results??[])}
    if(body.action==="orders"){const r=await db.prepare("SELECT o.*,c.name customer_name,c.phone customer_phone,c.email customer_email,c.address customer_address,c.city customer_city,c.state customer_state,c.pincode customer_pincode,s.id shipment_id,s.courier,s.awb,s.status shipment_status,s.tracking_url FROM orders o JOIN customers c ON c.id=o.customer_id LEFT JOIN shipments s ON s.order_id=o.id ORDER BY o.created_at DESC").all();return Response.json(r.results??[])}
    if(body.action==="businessSettings"){const r=await db.prepare("SELECT * FROM business_settings WHERE id=1").first();return Response.json(r??{id:1,legal_name:"BestBeautys",brand_name:"ISHVARI",state:"Telangana"})}
    if(body.action==="updateBusinessSettings"){const d=body;await db.prepare("INSERT INTO business_settings (id,legal_name,brand_name,gstin,phone,email,address,city,state,pincode,updated_at) VALUES (1,?,?,?,?,?,?,?,?,?,datetime('now')) ON CONFLICT(id) DO UPDATE SET legal_name=excluded.legal_name,brand_name=excluded.brand_name,gstin=excluded.gstin,phone=excluded.phone,email=excluded.email,address=excluded.address,city=excluded.city,state=excluded.state,pincode=excluded.pincode,updated_at=datetime('now')").bind(d.legalName||"BestBeautys",d.brandName||"ISHVARI",d.gstin||null,d.phone||null,d.email||null,d.address||null,d.city||null,d.state||"Telangana",d.pincode||null).run();return Response.json({ok:true})}
    if(body.action==="invoice"){if(typeof body.id!=="string"||!body.id)return Response.json({error:"Invalid invoice id"},{status:400});const order=await db.prepare("SELECT o.*,c.name customer_name,c.phone customer_phone,c.email customer_email,c.address customer_address,c.city customer_city,c.state customer_state,c.pincode customer_pincode FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.id=?").bind(body.id).first<any>();if(!order)return Response.json(null);const items=await db.prepare("SELECT oi.*,p.sku product_sku FROM order_items oi LEFT JOIN products p ON p.id=oi.product_id WHERE oi.order_id=? ORDER BY oi.rowid").bind(body.id).all();const seller=await db.prepare("SELECT * FROM business_settings WHERE id=1").first();const ship=await db.prepare("SELECT * FROM shipments WHERE order_id=? ORDER BY created_at DESC LIMIT 1").bind(body.id).first();return Response.json({order,items:items.results??[],seller:seller??null,shipment:ship??null})}
    if(body.action==="createCustomer"){const d=body; if(typeof d.name!=="string"||d.name.length<2||typeof d.phone!=="string"||d.phone.length<8)return Response.json({error:"Invalid customer"},{status:400});const id=crypto.randomUUID();await db.prepare("INSERT INTO customers (id,name,phone,email,address,city,state,pincode) VALUES (?,?,?,?,?,?,?,?)").bind(id,d.name,d.phone,d.email||null,d.address||null,d.city||null,d.state||null,d.pincode||null).run();return Response.json({id})}
    if(body.action==="createOrder"){if(typeof body.customerId!=="string"||typeof body.productName!=="string"||!Number.isInteger(body.quantity)||body.quantity<1||!Number.isInteger(body.unitPricePaise)||body.unitPricePaise<0)return Response.json({error:"Invalid order"},{status:400});const id=crypto.randomUUID(),itemId=crypto.randomUUID(),shipId=crypto.randomUUID(),orderNo="ISH-"+new Date().toISOString().slice(0,10).replace(/-/g,"")+"-"+crypto.randomUUID().slice(0,8).toUpperCase();const subtotal=body.quantity*body.unitPricePaise,gst=Math.round(subtotal*(Number(body.gstPercent)||0)/100),total=subtotal+gst+(body.shippingPaise||0);await db.batch([db.prepare("INSERT INTO orders (id,order_no,source,customer_id,status,payment_status,payment_mode,subtotal_paise,shipping_paise,gst_paise,total_paise) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,orderNo,body.source||"CRM",body.customerId,"NEW",body.paymentMode==="COD"?"PENDING":"PAID",body.paymentMode||"PREPAID",subtotal,body.shippingPaise||0,gst,total),db.prepare("INSERT INTO order_items (id,order_id,product_id,product_name,quantity,unit_price_paise,total_paise) VALUES (?,?,?,?,?,?,?)").bind(itemId,id,body.productId||null,body.productName,body.quantity,body.unitPricePaise,subtotal),db.prepare("INSERT INTO shipments (id,order_id) VALUES (?,?)").bind(shipId,id)]);return Response.json({id,orderNo})}
    if(body.action==="updateOrderStatus"){const allowed=["NEW","PACKED","SHIPPED","OUT_FOR_DELIVERY","DELIVERED","RTO","CANCELLED"];if(!allowed.includes(body.status))return Response.json({error:"Invalid status"},{status:400});await db.prepare("UPDATE orders SET status=?,updated_at=datetime('now') WHERE id=?").bind(body.status,body.id).run();return Response.json({ok:true})}
    if(body.action==="updateProduct"){if(typeof body.id!=="string"||typeof body.name!=="string"||!body.name.trim()||!Number.isInteger(body.pricePaise)||body.pricePaise<0||!Number.isInteger(body.stock)||body.stock<0)return Response.json({error:"Invalid product"},{status:400});await db.prepare("UPDATE products SET name=?,sku=?,price_paise=?,gst_percent=?,stock=? WHERE id=?").bind(body.name.trim(),body.sku||null,body.pricePaise,Number(body.gstPercent)||0,body.stock,body.id).run();return Response.json({ok:true})}
    if(body.action==="updateShipment"){const allowed=["NOT_CREATED","READY","SHIPPED","OUT_FOR_DELIVERY","DELIVERED","RTO"];if(!allowed.includes(body.status)||typeof body.id!=="string")return Response.json({error:"Invalid shipment"},{status:400});await db.prepare("UPDATE shipments SET courier=?,awb=?,status=?,tracking_url=?,shipped_at=CASE WHEN ? IN ('SHIPPED','OUT_FOR_DELIVERY') THEN COALESCE(shipped_at,datetime('now')) ELSE shipped_at END,delivered_at=CASE WHEN ?='DELIVERED' THEN COALESCE(delivered_at,datetime('now')) ELSE delivered_at END WHERE id=?").bind(body.courier||null,body.awb||null,body.status,body.trackingUrl||null,body.status,body.status,body.id).run();return Response.json({ok:true})}
    return Response.json({error:"Unknown action"},{status:400});
  }}}
});
type Tab = "Overview"|"Orders"|"Customers"|"Shipments"|"Billing"|"Products"|"Returns";
const money=(p:number)=>"₹"+(p/100).toLocaleString("en-IN",{minimumFractionDigits:2});
const statusTone=(s:string)=>({NEW:"blue",PACKED:"amber",SHIPPED:"green",OUT_FOR_DELIVERY:"green",DELIVERED:"green",RTO:"red",CANCELLED:"red"} as Record<string,string>)[s]||"slate";

function CRM(){
 const [authed,setAuthed]=useState<boolean|null>(null),[password,setPassword]=useState(""),[loginError,setLoginError]=useState(""); const [tracking,setTracking]=useState<any|undefined>(undefined);
 const [tab,setTab]=useState<Tab>("Overview"),[data,setData]=useState<any>({metrics:{orders:0,customers:0,shipped:0,delivered:0,pending:0},recent:[]});
 const [customers,setCustomers]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[showCustomer,setShowCustomer]=useState(false),[showOrder,setShowOrder]=useState(false),[loading,setLoading]=useState(false);
 async function refresh(){try{const [d,c,o,p]=await Promise.all([getDashboard(),getCustomers(),getOrders(),getProducts()]);setData(d);setCustomers(c as any[]);setOrders(o as any[]);setProducts(p as any[]);setAuthed(true)}catch{setAuthed(false)}}
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("track");if(id){getPublicTracking(id).then(setTracking).catch(()=>setTracking(null));}else{void refresh()}},[]);
 async function login(e:React.FormEvent){e.preventDefault();setLoading(true);setLoginError("");try{await crmLogin(password);setPassword("");await refresh()}catch{setLoginError("Invalid password or CRM setup is incomplete.")}setLoading(false)}
 if(tracking!==undefined)return <Tracking row={tracking}/>;
 if(authed===null)return <div className="center-screen"><div className="loader"/></div>;
 if(!authed)return <div className="center-screen"><div className="loader"/></div>;
 return <div className="crm-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">I</div><div><div className="brand-name">ISHVARI</div><div className="brand-sub">BUSINESS CRM</div></div></div><nav>{(["Overview","Orders","Customers","Shipments","Billing","Products","Returns"] as Tab[]).map(x=><button key={x} className={tab===x?"nav-item active":"nav-item"} onClick={()=>setTab(x)}><span className="nav-dot"/>{x}</button>)}</nav><div className="sidebar-bottom"><div className="secure"><span>●</span> Private workspace</div><button className="logout" onClick={async()=>{await logout();setAuthed(false)}}>Sign out</button></div></aside>
 <main className="main"><header className="topbar"><div><div className="eyebrow">BESTBEAUTYS · ISHVARI</div><h1>{tab}</h1></div><div className="top-actions"><button className="ghost" onClick={()=>refresh()}>Refresh</button>{tab==="Customers"&&<button className="primary" onClick={()=>setShowCustomer(true)}>+ Customer</button>}{tab==="Orders"&&<button className="primary" onClick={()=>setShowOrder(true)}>+ New Order</button>}</div></header>
 {tab==="Overview"&&<Overview data={data} onOrders={()=>setTab("Orders")}/>} {tab==="Customers"&&<Customers rows={customers}/>} {tab==="Orders"&&<Orders rows={orders} onStatus={async(id,s)=>{await updateOrderStatus({data:{id,status:s as any}});await refresh()}}/>} {tab==="Shipments"&&<Shipments rows={orders} onSaved={refresh}/>} {tab==="Billing"&&<Billing rows={orders}/>} {tab==="Products"&&<Products rows={products} onSaved={refresh}/>} {tab==="Returns"&&<Returns rows={orders}/>}
 </main>{showCustomer&&<CustomerModal onClose={()=>setShowCustomer(false)} onSaved={async()=>{setShowCustomer(false);await refresh()}}/>}{showOrder&&<OrderModal customers={customers} products={products} onClose={()=>setShowOrder(false)} onSaved={async()=>{setShowOrder(false);await refresh()}}/>}</div>
}

function Login({password,setPassword,onSubmit,error,loading}:{password:string,setPassword:(v:string)=>void,onSubmit:(e:React.FormEvent)=>void,error:string,loading:boolean}){return <div className="login-page"><div className="login-card"><div className="brand centered"><div className="brand-mark">I</div><div><div className="brand-name">ISHVARI</div><div className="brand-sub">BUSINESS CRM</div></div></div><div className="login-copy"><h1>Welcome back.</h1><p>Private operations dashboard for BestBeautys.</p></div><form onSubmit={onSubmit}><label>CRM password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus placeholder="Enter your password"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?"Signing in…":"Sign in"}</button></form><div className="login-note">Your business data stays inside the private CRM workspace.</div></div></div>}

function Overview({data,onOrders}:{data:any,onOrders:()=>void}){return <section className="content"><div className="metric-grid"><Metric label="Total orders" value={data.metrics.orders}/><Metric label="Customers" value={data.metrics.customers}/><Metric label="Ready / packed" value={data.metrics.pending}/><Metric label="Shipped" value={data.metrics.shipped}/><Metric label="Delivered" value={data.metrics.delivered}/></div><div className="section-grid"><div className="panel"><div className="panel-head"><div><div className="section-kicker">ORDER FLOW</div><h2>Recent orders</h2></div><button className="text-button" onClick={onOrders}>View all →</button></div>{data.recent.length?<Table rows={data.recent}/>:<Empty title="No orders yet" text="Your first WhatsApp, Shopify or CRM order will appear here."/>}</div><div className="panel ritual"><div className="section-kicker">OPERATIONS</div><h2>ISHVARI control center</h2><p>One place for customers, orders, payments, shipping and RTO follow-up.</p><div className="flow"><span>Order</span><i>→</i><span>Pack</span><i>→</i><span>Shiprocket</span><i>→</i><span>Deliver</span></div><div className="small-note">Shiprocket and WhatsApp API credentials can be connected later without changing the CRM structure.</div></div></div></section>}
function Tracking({row}:{row:any}){return <div className="tracking-page"><div className="tracking-card"><div className="brand centered"><div className="brand-mark">I</div><div><div className="brand-name">ISHVARI</div><div className="brand-sub">TRACKING</div></div></div>{row?<><div className="section-kicker">SHIPMENT STATUS</div><h1>{row.order_no}</h1><div className="tracking-status">{row.status.replaceAll("_"," ")}</div>{row.courier&&<p>Courier: <b>{row.courier}</b></p>}{row.awb&&<p>AWB: <b>{row.awb}</b></p>}</>:<p>Tracking details are not available.</p>}</div></div>}
function Metric({label,value}:{label:string,value:number}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value.toLocaleString("en-IN")}</div><div className="metric-line"/></div>}
function Badge({status}:{status:string}){return <span className={"badge "+statusTone(status)}>{status.replaceAll("_"," ")}</span>}
function Empty({title,text}:{title:string,text:string}){return <div className="empty"><div className="empty-mark">I</div><h3>{title}</h3><p>{text}</p></div>}
function Table({rows}:{rows:any[]}){return <div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">{r.order_no}</td><td>{r.name||r.customer_name}<small>{r.phone||r.customer_phone}</small></td><td><Badge status={r.status}/></td><td>{money(r.total_paise)}</td><td>{new Date(r.created_at+"Z").toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>}

function Customers({rows}:{rows:any[]}){return <section className="content"><div className="panel"><div className="panel-head"><div><div className="section-kicker">CUSTOMER BOOK</div><h2>{rows.length} customers</h2></div></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Location</th><th>Added</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">{r.name}</td><td>{r.phone}</td><td>{r.email||"—"}</td><td>{[r.city,r.state,r.pincode].filter(Boolean).join(", ")||"—"}</td><td>{new Date(r.created_at+"Z").toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>:<Empty title="Customer book is empty" text="Add your first customer to start taking direct WhatsApp orders."/ >}</div></section>}
function Orders({rows,onStatus}:{rows:any[],onStatus:(id:string,s:string)=>void}){return <section className="content"><div className="panel"><div className="panel-head"><div><div className="section-kicker">ORDER MANAGEMENT</div><h2>{rows.length} orders</h2></div></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Payment</th><th>Status</th><th>Shipment</th><th>Total</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">{r.order_no}<small>{r.source}</small></td><td>{r.customer_name}<small>{r.customer_phone}</small></td><td>{r.payment_status}<small>{r.payment_mode||""}</small></td><td><select className="status-select" value={r.status} onChange={e=>onStatus(r.id,e.target.value)}>{["NEW","PACKED","SHIPPED","OUT_FOR_DELIVERY","DELIVERED","RTO","CANCELLED"].map(s=><option key={s}>{s}</option>)}</select></td><td>{r.awb?<><b>{r.courier}</b><small>{r.awb}</small></>:"Not created"}</td><td className="strong">{money(r.total_paise)}</td></tr>)}</tbody></table></div>:<Empty title="No orders" text="Create an order from WhatsApp, Shopify or directly in the CRM."/>}</div></section>}
function Shipments({rows,onSaved}:{rows:any[],onSaved:()=>Promise<void>}){return <section className="content"><div className="panel"><div className="section-kicker">SHIPMENT DESK</div><h2>AWB & tracking</h2><div className="info-banner">Enter AWB after packing. This manual flow is ready now; Shiprocket API can be connected later without changing the order records.</div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Courier</th><th>AWB</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(r=><ShipmentRow key={r.id} row={r} onSaved={onSaved}/>)}</tbody></table></div>:<Empty title="No shipments yet" text="Create an order first; its shipment record will appear here."/>}</div></section>}
function ShipmentRow({row,onSaved}:{row:any,onSaved:()=>Promise<void>}){const [courier,setCourier]=useState(row.courier||"");const [awb,setAwb]=useState(row.awb||"");const [status,setStatus]=useState(row.shipment_status||"NOT_CREATED");const [busy,setBusy]=useState(false);return <tr><td className="strong">{row.order_no}</td><td>{row.customer_name}<small>{row.customer_phone}</small></td><td><input className="table-input" value={courier} onChange={e=>setCourier(e.target.value)} placeholder="Delhivery"/></td><td><input className="table-input" value={awb} onChange={e=>setAwb(e.target.value)} placeholder="AWB number"/></td><td><select className="status-select" value={status} onChange={e=>setStatus(e.target.value)}>{["NOT_CREATED","READY","SHIPPED","OUT_FOR_DELIVERY","DELIVERED","RTO"].map(x=><option key={x}>{x}</option>)}</select></td><td><button className="ghost small" disabled={busy} onClick={async()=>{setBusy(true);await updateShipment({data:{id:row.shipment_id,courier,awb,status,trackingUrl:awb?`https://www.delhivery.com/track/package/?waybill=${encodeURIComponent(awb)}`:""}});await onSaved();setBusy(false)}}>{busy?"Saving…":"Save"}</button></td></tr>}
function Billing({rows}:{rows:any[]}){const [invoice,setInvoice]=useState<any|null>(null);const [settings,setSettings]=useState<any>({legal_name:"BestBeautys",brand_name:"ISHVARI",gstin:"",phone:"",email:"",address:"",city:"",state:"Telangana",pincode:""});const [showSettings,setShowSettings]=useState(false);const [saving,setSaving]=useState(false);useEffect(()=>{getBusinessSettings().then(setSettings).catch(()=>{})},[]);return <section className="content"><div className="panel"><div className="panel-head"><div><div className="section-kicker">BESTBEAUTYS BILLING</div><h2>Invoices</h2></div><button className="ghost" onClick={()=>setShowSettings(v=>!v)}>{showSettings?"Close settings":"Business details"}</button></div>{showSettings&&<BusinessSettings settings={settings} setSettings={setSettings} saving={saving} onSave={async()=>{setSaving(true);await updateBusinessSettings({data:{legalName:settings.legal_name,brandName:settings.brand_name,gstin:settings.gstin,phone:settings.phone,email:settings.email,address:settings.address,city:settings.city,state:settings.state,pincode:settings.pincode}});setSaving(false);setShowSettings(false)}}/>}{rows.length?<div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">INV-{r.order_no.replace("ISH-","")}</td><td>{r.order_no}</td><td>{r.customer_name}<small>{r.customer_phone}</small></td><td>{money(r.total_paise)}</td><td>{r.payment_mode||"—"}</td><td><button className="ghost small" onClick={async()=>setInvoice(await getInvoice(r.id))}>View / Print</button></td></tr>)}</tbody></table></div>:<Empty title="No invoices yet" text="Invoices will appear automatically when orders are created."/>}<div className="invoice-note">Seller: <b>{settings.legal_name||"BestBeautys"}</b> · Brand: <b>{settings.brand_name||"ISHVARI"}</b>. Add GSTIN and seller address under Business details before issuing production invoices.</div></div>{invoice&&<InvoiceView data={invoice} onClose={()=>setInvoice(null)}/>}</section>}
function BusinessSettings({settings,setSettings,saving,onSave}:{settings:any,setSettings:(v:any)=>void,saving:boolean,onSave:()=>Promise<void>}){return <div className="settings-box"><div className="section-kicker">INVOICE HEADER</div><div className="form-grid"><label>Legal seller name<input value={settings.legal_name||""} onChange={e=>setSettings({...settings,legal_name:e.target.value})}/></label><label>Brand name<input value={settings.brand_name||""} onChange={e=>setSettings({...settings,brand_name:e.target.value})}/></label><label>GSTIN<input value={settings.gstin||""} placeholder="Enter GSTIN" onChange={e=>setSettings({...settings,gstin:e.target.value.toUpperCase()})}/></label><label>Phone<input value={settings.phone||""} onChange={e=>setSettings({...settings,phone:e.target.value})}/></label><label>Email<input value={settings.email||""} onChange={e=>setSettings({...settings,email:e.target.value})}/></label><label>Pincode<input value={settings.pincode||""} onChange={e=>setSettings({...settings,pincode:e.target.value})}/></label><label className="span-2">Address<input value={settings.address||""} onChange={e=>setSettings({...settings,address:e.target.value})}/></label><label>City<input value={settings.city||""} onChange={e=>setSettings({...settings,city:e.target.value})}/></label><label>State<input value={settings.state||"Telangana"} onChange={e=>setSettings({...settings,state:e.target.value})}/></label></div><div className="modal-actions"><button className="primary" onClick={onSave} disabled={saving}>{saving?"Saving…":"Save business details"}</button></div></div>}
function InvoiceView({data,onClose}:{data:any,onClose:()=>void}){const o=data.order,s=data.seller||{};const items=data.items||[];const sameState=(String(o.customer_state||"").trim().toLowerCase()===String(s.state||"Telangana").trim().toLowerCase());const gstRate=o.subtotal_paise?Math.round((o.gst_paise/o.subtotal_paise)*10000)/100:0;const cgst=sameState?o.gst_paise/2:0;const sgst=sameState?o.gst_paise/2:0;const igst=sameState?0:o.gst_paise;return <div className="invoice-backdrop"><div className="invoice-shell"><div className="invoice-actions"><button className="ghost" onClick={onClose}>Close</button><button className="primary" onClick={()=>window.print()}>Print / Save PDF</button></div><div className="invoice-print"><div className="invoice-head"><div><div className="invoice-brand">{s.brand_name||"ISHVARI"}</div><div className="invoice-seller">{s.legal_name||"BestBeautys"}</div><div className="invoice-meta">{s.address&&<>{s.address}<br/></>}{[s.city,s.state,s.pincode].filter(Boolean).join(", ")}{s.phone&&<> · {s.phone}</>}{s.email&&<> · {s.email}</>}</div>{s.gstin&&<div className="invoice-meta"><b>GSTIN:</b> {s.gstin}</div>}</div><div className="invoice-title"><div>TAX INVOICE</div><b>INV-{o.order_no.replace("ISH-","")}</b><span>Date: {new Date(o.created_at+"Z").toLocaleDateString("en-IN")}</span></div></div><div className="invoice-two-col"><div><div className="invoice-label">BILL TO</div><b>{o.customer_name}</b><div>{o.customer_address||""}</div><div>{[o.customer_city,o.customer_state,o.customer_pincode].filter(Boolean).join(", ")}</div><div>{o.customer_phone}</div>{o.customer_email&&<div>{o.customer_email}</div>}</div><div><div className="invoice-label">ORDER</div><div><b>{o.order_no}</b></div><div>Payment: {o.payment_mode||"—"} · {o.payment_status}</div>{data.shipment?.awb&&<div>AWB: {data.shipment.awb}</div>}</div></div><table className="invoice-table"><thead><tr><th>#</th><th>Product</th><th>SKU</th><th>Qty</th><th>Rate</th><th>Taxable</th><th>GST</th><th>Total</th></tr></thead><tbody>{items.map((it:any,i:number)=><tr key={it.id}><td>{i+1}</td><td>{it.product_name}</td><td>{it.product_sku||"—"}</td><td>{it.quantity}</td><td>{money(it.unit_price_paise)}</td><td>{money(it.total_paise)}</td><td>{gstRate}%</td><td>{money(it.total_paise+Math.round(it.total_paise*gstRate/100))}</td></tr>)}</tbody></table><div className="invoice-summary"><div className="invoice-tax-note">{sameState?<><div>CGST: {money(cgst)}</div><div>SGST: {money(sgst)}</div></>:<div>IGST: {money(igst)}</div>}<div>Shipping: {money(o.shipping_paise)}</div></div><div className="invoice-grand"><span>Grand Total</span><b>{money(o.total_paise)}</b></div></div><div className="invoice-footer"><div><b>Amount received / due:</b> {o.payment_status==="PAID"?"Paid":"Due"}</div><div>Thank you for choosing {s.brand_name||"ISHVARI"}.</div></div></div></div></div>}
function Products({rows,onSaved}:{rows:any[],onSaved:()=>Promise<void>}){return <section className="content"><div className="panel"><div className="section-kicker">PRODUCT CATALOG</div><h2>ISHVARI products</h2>{rows.length?<div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>GST %</th><th>Stock</th><th>Action</th></tr></thead><tbody>{rows.map(r=><ProductRow key={r.id} row={r} onSaved={onSaved}/>)}</tbody></table></div>:<Empty title="No products" text="Add products in the CRM database before taking orders."/>}</div></section>}
function ProductRow({row,onSaved}:{row:any,onSaved:()=>Promise<void>}){const [name,setName]=useState(row.name);const [sku,setSku]=useState(row.sku||"");const [price,setPrice]=useState((row.price_paise/100).toFixed(2));const [gst,setGst]=useState(String(row.gst_percent??18));const [stock,setStock]=useState(String(row.stock??0));const [busy,setBusy]=useState(false);return <tr><td><input className="table-input product-name-input" value={name} onChange={e=>setName(e.target.value)}/></td><td><input className="table-input" value={sku} onChange={e=>setSku(e.target.value)}/></td><td><input className="table-input price-input" type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)}/></td><td><input className="table-input gst-input" type="number" min="0" value={gst} onChange={e=>setGst(e.target.value)}/></td><td><input className="table-input stock-input" type="number" min="0" value={stock} onChange={e=>setStock(e.target.value)}/></td><td><button className="ghost small" disabled={busy} onClick={async()=>{setBusy(true);await updateProduct({data:{id:row.id,name,sku,pricePaise:Math.round(Number(price)*100),gstPercent:Number(gst),stock:Number(stock)}});await onSaved();setBusy(false)}}>{busy?"Saving…":"Save"}</button></td></tr>}
function Returns({rows}:{rows:any[]}){const rto=rows.filter(x=>x.status==="RTO");return <section className="content"><div className="panel"><div className="section-kicker">AFTER SALES</div><h2>Returns & RTO</h2>{rto.length?<div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>{rto.map(r=><tr key={r.id}><td>{r.order_no}</td><td>{r.customer_name}</td><td><Badge status="RTO"/></td><td>{money(r.total_paise)}</td></tr>)}</tbody></table></div>:<Empty title="No RTO orders" text="RTO and return cases will surface here for follow-up."/ >}</div></section>}

function CustomerModal({onClose,onSaved}:{onClose:()=>void,onSaved:()=>void}){const [f,setF]=useState({name:"",phone:"",email:"",address:"",city:"",state:"Telangana",pincode:""});const [busy,setBusy]=useState(false);return <Modal title="Add customer" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);await createCustomer({data:f});await onSaved()}}><Fields fields={f} setF={setF}/><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save customer"}</button></div></form></Modal>}
function Fields({fields,setF}:{fields:any,setF:(x:any)=>void}){return <div className="form-grid"><label>Name<input required value={fields.name} onChange={e=>setF({...fields,name:e.target.value})}/></label><label>Phone<input required value={fields.phone} onChange={e=>setF({...fields,phone:e.target.value})}/></label><label>Email<input type="email" value={fields.email} onChange={e=>setF({...fields,email:e.target.value})}/></label><label>Pincode<input value={fields.pincode} onChange={e=>setF({...fields,pincode:e.target.value})}/></label><label className="span-2">Address<input value={fields.address} onChange={e=>setF({...fields,address:e.target.value})}/></label><label>City<input value={fields.city} onChange={e=>setF({...fields,city:e.target.value})}/></label><label>State<input value={fields.state} onChange={e=>setF({...fields,state:e.target.value})}/></label></div>}
function OrderModal({customers,products,onClose,onSaved}:{customers:any[],products:any[],onClose:()=>void,onSaved:()=>void}){const first=products[0];const [f,setF]=useState({customerId:customers[0]?.id||"",productId:first?.id||"",productName:first?.name||"Ishvari Scalp Balance Oil",quantity:1,unitPricePaise:first?.price_paise||39900,gstPercent:first?.gst_percent??18,paymentMode:"PREPAID" as "PREPAID"|"COD"|"OTHER",shippingPaise:0,source:"CRM" as "CRM"|"WHATSAPP"|"SHOPIFY"});const [busy,setBusy]=useState(false);const subtotal=f.quantity*f.unitPricePaise;const gst=Math.round(subtotal*Number(f.gstPercent||0)/100);return <Modal title="Create order" onClose={onClose}>{!customers.length?<div className="error">Add a customer first.</div>:!products.length?<div className="error">Add a product first.</div>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);await createOrder({data:f});await onSaved()}}><div className="form-grid"><label className="span-2">Customer<select value={f.customerId} onChange={e=>setF({...f,customerId:e.target.value})}>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label><label className="span-2">Product<select value={f.productId} onChange={e=>{const p=products.find(x=>x.id===e.target.value);setF({...f,productId:e.target.value,productName:p?.name||f.productName,unitPricePaise:p?.price_paise??f.unitPricePaise,gstPercent:p?.gst_percent??f.gstPercent})}}>{products.map(p=><option key={p.id} value={p.id}>{p.name} · ₹{(p.price_paise/100).toLocaleString("en-IN")}</option>)}</select></label><label>Quantity<input type="number" min="1" value={f.quantity} onChange={e=>setF({...f,quantity:Math.max(1,Number(e.target.value)||1)})}/></label><label>Unit price (₹)<input type="number" min="0" value={f.unitPricePaise/100} onChange={e=>setF({...f,unitPricePaise:Math.max(0,Math.round(Number(e.target.value)*100))})}/></label><label>Payment<select value={f.paymentMode} onChange={e=>setF({...f,paymentMode:e.target.value as any})}><option>PREPAID</option><option>COD</option><option>OTHER</option></select></label><label>Source<select value={f.source} onChange={e=>setF({...f,source:e.target.value as any})}><option>CRM</option><option>WHATSAPP</option><option>SHOPIFY</option></select></label></div><div className="order-total"><span>Subtotal <b>{money(subtotal)}</b></span><span>GST ({f.gstPercent}%) <b>{money(gst)}</b></span><span>Shipping <b>{money(f.shippingPaise)}</b></span><span>Total <b>{money(subtotal+gst+f.shippingPaise)}</b></span><small>Tax rate comes from the product catalog and can be edited there.</small></div><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Creating…":"Create order"}</button></div></form>}</Modal>}
function Modal({title,onClose,children}:{title:string,onClose:()=>void,children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-close" onClick={onClose}>×</button></div>{children}</div></div>}
