import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { createCustomer, createOrder, getCustomers, getDashboard, getOrders, updateOrderStatus } from "../lib/api/crm.functions";

export const Route = createFileRoute("/")({ component: CRM });
type Tab = "Overview"|"Orders"|"Customers"|"Shipments"|"Billing"|"Products"|"Returns";
const money=(p:number)=>"₹"+(p/100).toLocaleString("en-IN",{minimumFractionDigits:2});
const statusTone=(s:string)=>({NEW:"blue",PACKED:"amber",SHIPPED:"green",OUT_FOR_DELIVERY:"green",DELIVERED:"green",RTO:"red",CANCELLED:"red"} as Record<string,string>)[s]||"slate";

function CRM(){
 const [authed,setAuthed]=useState<boolean|null>(null),[password,setPassword]=useState(""),[loginError,setLoginError]=useState("");
 const [tab,setTab]=useState<Tab>("Overview"),[data,setData]=useState<any>({metrics:{orders:0,customers:0,shipped:0,delivered:0,pending:0},recent:[]});
 const [customers,setCustomers]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[showCustomer,setShowCustomer]=useState(false),[showOrder,setShowOrder]=useState(false),[loading,setLoading]=useState(false);
 async function refresh(){try{const [d,c,o]=await Promise.all([getDashboard(),getCustomers(),getOrders()]);setData(d);setCustomers(c as any[]);setOrders(o as any[]);setAuthed(true)}catch{setAuthed(false)}}
 useEffect(()=>{void refresh()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setLoading(true);setLoginError("");const r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(r.ok){setPassword("");await refresh()}else{const j=await r.json().catch(()=>({}));setLoginError(j.error||"Login failed")}setLoading(false)}
 if(authed===null)return <div className="center-screen"><div className="loader"/></div>;
 if(!authed)return <Login password={password} setPassword={setPassword} onSubmit={login} error={loginError} loading={loading}/>;
 return <div className="crm-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">I</div><div><div className="brand-name">ISHVARI</div><div className="brand-sub">BUSINESS CRM</div></div></div><nav>{(["Overview","Orders","Customers","Shipments","Billing","Products","Returns"] as Tab[]).map(x=><button key={x} className={tab===x?"nav-item active":"nav-item"} onClick={()=>setTab(x)}><span className="nav-dot"/>{x}</button>)}</nav><div className="sidebar-bottom"><div className="secure"><span>●</span> Private workspace</div><button className="logout" onClick={async()=>{await fetch("/api/logout",{method:"POST"});setAuthed(false)}}>Sign out</button></div></aside>
 <main className="main"><header className="topbar"><div><div className="eyebrow">BESTBEAUTYS · ISHVARI</div><h1>{tab}</h1></div><div className="top-actions"><button className="ghost" onClick={()=>refresh()}>Refresh</button>{tab==="Customers"&&<button className="primary" onClick={()=>setShowCustomer(true)}>+ Customer</button>}{tab==="Orders"&&<button className="primary" onClick={()=>setShowOrder(true)}>+ New Order</button>}</div></header>
 {tab==="Overview"&&<Overview data={data} onOrders={()=>setTab("Orders")}/>} {tab==="Customers"&&<Customers rows={customers}/>} {tab==="Orders"&&<Orders rows={orders} onStatus={async(id,s)=>{await updateOrderStatus({data:{id,status:s as any}});await refresh()}}/>} {tab==="Shipments"&&<Shipments rows={orders}/>} {tab==="Billing"&&<Billing rows={orders}/>} {tab==="Products"&&<Products/>} {tab==="Returns"&&<Returns rows={orders}/>}
 </main>{showCustomer&&<CustomerModal onClose={()=>setShowCustomer(false)} onSaved={async()=>{setShowCustomer(false);await refresh()}}/>}{showOrder&&<OrderModal customers={customers} onClose={()=>setShowOrder(false)} onSaved={async()=>{setShowOrder(false);await refresh()}}/>}</div>
}

function Login({password,setPassword,onSubmit,error,loading}:{password:string,setPassword:(v:string)=>void,onSubmit:(e:React.FormEvent)=>void,error:string,loading:boolean}){return <div className="login-page"><div className="login-card"><div className="brand centered"><div className="brand-mark">I</div><div><div className="brand-name">ISHVARI</div><div className="brand-sub">BUSINESS CRM</div></div></div><div className="login-copy"><h1>Welcome back.</h1><p>Private operations dashboard for BestBeautys.</p></div><form onSubmit={onSubmit}><label>CRM password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus placeholder="Enter your password"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?"Signing in…":"Sign in"}</button></form><div className="login-note">Your business data stays inside the private CRM workspace.</div></div></div>}

function Overview({data,onOrders}:{data:any,onOrders:()=>void}){return <section className="content"><div className="metric-grid"><Metric label="Total orders" value={data.metrics.orders}/><Metric label="Customers" value={data.metrics.customers}/><Metric label="Ready / packed" value={data.metrics.pending}/><Metric label="Shipped" value={data.metrics.shipped}/><Metric label="Delivered" value={data.metrics.delivered}/></div><div className="section-grid"><div className="panel"><div className="panel-head"><div><div className="section-kicker">ORDER FLOW</div><h2>Recent orders</h2></div><button className="text-button" onClick={onOrders}>View all →</button></div>{data.recent.length?<Table rows={data.recent}/>:<Empty title="No orders yet" text="Your first WhatsApp, Shopify or CRM order will appear here."/>}</div><div className="panel ritual"><div className="section-kicker">OPERATIONS</div><h2>ISHVARI control center</h2><p>One place for customers, orders, payments, shipping and RTO follow-up.</p><div className="flow"><span>Order</span><i>→</i><span>Pack</span><i>→</i><span>Shiprocket</span><i>→</i><span>Deliver</span></div><div className="small-note">Shiprocket and WhatsApp API credentials can be connected later without changing the CRM structure.</div></div></div></section>}
function Metric({label,value}:{label:string,value:number}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value.toLocaleString("en-IN")}</div><div className="metric-line"/></div>}
function Badge({status}:{status:string}){return <span className={"badge "+statusTone(status)}>{status.replaceAll("_"," ")}</span>}
function Empty({title,text}:{title:string,text:string}){return <div className="empty"><div className="empty-mark">I</div><h3>{title}</h3><p>{text}</p></div>}
function Table({rows}:{rows:any[]}){return <div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">{r.order_no}</td><td>{r.name||r.customer_name}<small>{r.phone||r.customer_phone}</small></td><td><Badge status={r.status}/></td><td>{money(r.total_paise)}</td><td>{new Date(r.created_at+"Z").toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>}

function Customers({rows}:{rows:any[]}){return <section className="content"><div className="panel"><div className="panel-head"><div><div className="section-kicker">CUSTOMER BOOK</div><h2>{rows.length} customers</h2></div></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Location</th><th>Added</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">{r.name}</td><td>{r.phone}</td><td>{r.email||"—"}</td><td>{[r.city,r.state,r.pincode].filter(Boolean).join(", ")||"—"}</td><td>{new Date(r.created_at+"Z").toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>:<Empty title="Customer book is empty" text="Add your first customer to start taking direct WhatsApp orders."/ >}</div></section>}
function Orders({rows,onStatus}:{rows:any[],onStatus:(id:string,s:string)=>void}){return <section className="content"><div className="panel"><div className="panel-head"><div><div className="section-kicker">ORDER MANAGEMENT</div><h2>{rows.length} orders</h2></div></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Payment</th><th>Status</th><th>Shipment</th><th>Total</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">{r.order_no}<small>{r.source}</small></td><td>{r.customer_name}<small>{r.customer_phone}</small></td><td>{r.payment_status}<small>{r.payment_mode||""}</small></td><td><select className="status-select" value={r.status} onChange={e=>onStatus(r.id,e.target.value)}>{["NEW","PACKED","SHIPPED","OUT_FOR_DELIVERY","DELIVERED","RTO","CANCELLED"].map(s=><option key={s}>{s}</option>)}</select></td><td>{r.awb?<><b>{r.courier}</b><small>{r.awb}</small></>:"Not created"}</td><td className="strong">{money(r.total_paise)}</td></tr>)}</tbody></table></div>:<Empty title="No orders" text="Create an order from WhatsApp, Shopify or directly in the CRM."/>}</div></section>}
function Shipments({rows}:{rows:any[]}){return <section className="content"><div className="panel"><div className="section-kicker">SHIPMENT DESK</div><h2>AWB & tracking</h2><div className="info-banner">Shiprocket integration slot is ready. Once connected, courier selection, AWB creation, tracking sync and NDR/RTO updates can flow into this screen.</div><Table rows={rows}/></div></section>}
function Billing({rows}:{rows:any[]}){return <section className="content"><div className="panel"><div className="section-kicker">BESTBEAUTYS BILLING</div><h2>Invoices</h2>{rows.length?<div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Order</th><th>Customer</th><th>Total</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="strong">INV-{r.order_no.replace("ISH-","")}</td><td>{r.order_no}</td><td>{r.customer_name}</td><td>{money(r.total_paise)}</td><td><button className="ghost small" onClick={()=>window.print()}>Print</button></td></tr>)}</tbody></table></div>:<Empty title="No invoices yet" text="Invoices will appear automatically when orders are created."/ >}<div className="invoice-note">Seller: <b>BestBeautys</b> · Brand: <b>ISHVARI</b>. GST details can be completed in Settings before production billing.</div></div></section>}
function Products(){return <section className="content"><div className="panel"><div className="section-kicker">PRODUCT CATALOG</div><h2>ISHVARI products</h2><div className="product-grid">{["Ishvari Scalp Balance Oil","Ishvari Fine Hair Oil","Ishvari Curly & Thick Hair Oil","Ishvari Grey Hair Ritual Oil"].map((x,i)=><div className="product-card" key={x}><div className="product-num">0{i+1}</div><h3>{x}</h3><p>Catalog item ready for pricing, stock and SKU management.</p></div>)}</div></div></section>}
function Returns({rows}:{rows:any[]}){const rto=rows.filter(x=>x.status==="RTO");return <section className="content"><div className="panel"><div className="section-kicker">AFTER SALES</div><h2>Returns & RTO</h2>{rto.length?<div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>{rto.map(r=><tr key={r.id}><td>{r.order_no}</td><td>{r.customer_name}</td><td><Badge status="RTO"/></td><td>{money(r.total_paise)}</td></tr>)}</tbody></table></div>:<Empty title="No RTO orders" text="RTO and return cases will surface here for follow-up."/ >}</div></section>}

function CustomerModal({onClose,onSaved}:{onClose:()=>void,onSaved:()=>void}){const [f,setF]=useState({name:"",phone:"",email:"",address:"",city:"",state:"Telangana",pincode:""});const [busy,setBusy]=useState(false);return <Modal title="Add customer" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);await createCustomer({data:f});await onSaved()}}><Fields fields={f} setF={setF}/><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save customer"}</button></div></form></Modal>}
function Fields({fields,setF}:{fields:any,setF:(x:any)=>void}){return <div className="form-grid"><label>Name<input required value={fields.name} onChange={e=>setF({...fields,name:e.target.value})}/></label><label>Phone<input required value={fields.phone} onChange={e=>setF({...fields,phone:e.target.value})}/></label><label>Email<input type="email" value={fields.email} onChange={e=>setF({...fields,email:e.target.value})}/></label><label>Pincode<input value={fields.pincode} onChange={e=>setF({...fields,pincode:e.target.value})}/></label><label className="span-2">Address<input value={fields.address} onChange={e=>setF({...fields,address:e.target.value})}/></label><label>City<input value={fields.city} onChange={e=>setF({...fields,city:e.target.value})}/></label><label>State<input value={fields.state} onChange={e=>setF({...fields,state:e.target.value})}/></label></div>}
function OrderModal({customers,onClose,onSaved}:{customers:any[],onClose:()=>void,onSaved:()=>void}){const [f,setF]=useState({customerId:customers[0]?.id||"",productName:"Ishvari Scalp Balance Oil",quantity:1,unitPricePaise:39900,paymentMode:"PREPAID" as "PREPAID"|"COD"|"OTHER",shippingPaise:0,source:"CRM" as "CRM"|"WHATSAPP"|"SHOPIFY"});const [busy,setBusy]=useState(false);return <Modal title="Create order" onClose={onClose}>{!customers.length?<div className="error">Add a customer first.</div>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);await createOrder({data:f});await onSaved()}}><div className="form-grid"><label className="span-2">Customer<select value={f.customerId} onChange={e=>setF({...f,customerId:e.target.value})}>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label><label className="span-2">Product<input value={f.productName} onChange={e=>setF({...f,productName:e.target.value})}/></label><label>Quantity<input type="number" min="1" value={f.quantity} onChange={e=>setF({...f,quantity:Number(e.target.value)})}/></label><label>Unit price (₹)<input type="number" min="0" value={f.unitPricePaise/100} onChange={e=>setF({...f,unitPricePaise:Math.round(Number(e.target.value)*100)})}/></label><label>Payment<select value={f.paymentMode} onChange={e=>setF({...f,paymentMode:e.target.value as any})}><option>PREPAID</option><option>COD</option><option>OTHER</option></select></label><label>Source<select value={f.source} onChange={e=>setF({...f,source:e.target.value as any})}><option>CRM</option><option>WHATSAPP</option><option>SHOPIFY</option></select></label></div><div className="order-total">Estimated total <b>{money(f.quantity*f.unitPricePaise+Math.round(f.quantity*f.unitPricePaise*.18)+f.shippingPaise)}</b><small>Includes 18% GST placeholder; final tax rules should be confirmed for your invoice setup.</small></div><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Creating…":"Create order"}</button></div></form>}</Modal>}
function Modal({title,onClose,children}:{title:string,onClose:()=>void,children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-close" onClick={onClose}>×</button></div>{children}</div></div>}
